Day-3-Python-Questions

- Initial questions on 11/27
- Follow up and clean up on 11/30


### to add:
- build managing of indexing and array position where nulls are located to either replace np.isnull and np.where or find another solution that meets the criteria. 


In [3]:
import numpy as np
import math
#2. check if there are duplicates in a string


In [62]:
class My_dynamic_array(object):
    '''
    1. Make a dynamically resizing array that doubles when full
    elements that are empty contain np.nan
    '''
    def __init__(self, init_size = 5):
        self.current_array = np.array([np.nan]*init_size)
        self.next_null_pos = 0
        self.remaining_null_in_array = init_size
    #         self.count_null = init_size
        
    def fill_array(self, array_size):
        tmp_array = np.empty(array_size)
        tmp_array.fill(np.nan)
        
        return np.append(self.current_array, tmp_array)

    def update_array(self, val, pos):
        self.current_array[pos] = val
        
        
    
    def track_next_null():
        '''#need to create a method that keeps track of the next null position because: 
            # what if a null is passed to the 2nd position, and that becomes the next open slot.
            # what if a val is passed to an open slot that exists but has other nulls prior to it.
        '''
        
        pass

    
    
    def add_element(self, val, pos = np.nan):
        '''
        add an element to the array.

        If pos value is empty, then add to the next open null position
            if no more null slots are availabe, then douple the length of the array and retry.
        
        if the pos argument is passed, then 
            check if the pos can legally be updated, ie, it exists.
                if not legal return a message to user.
                
                if legal, overwrite that position with the new value.
        '''
        
        #check if pos. is passed.
        if pos:
            #check if pos is legal
            if pos < len(self.current_array):
                #this is a legal pos.
                #update pos
        
                # first track if this is an update to a null and if that null is the next null 
                # also check if this a null addition that creates a new first null,
                # or overwrites the the next null with a null, 
                # or overwrites a null later in the list, so the next null remains as the next open slot, but later the 
                # next open slot will have to jump over a filled spot. 
                self.update_array(val, pos)
            else:
                print("this is not a legal position. position must be less then: " + str(len(self.current_array)))
        
        else:
            #no position passed            
            #check if there is an open slot.
            if len(self.current_array[np.isnan(self.current_array)]) > 0:
                #there is an open slot available.
                #add element to the next open slot. 
                self.update_array(val, np.where(np.isnan(x))[0][0])
            else:
                #double the length and add the value to the next 
                array_len = len(self.current_array)
                temp_array = np.array([np.nan]*array_len)
                np.append(self.current_array, temp_array)
                self.update_array(val, array_len)
        


In [63]:
a = My_dynamic_array()
print(a.current_array)
a.add_element(4)
print(a.current_array)
a.add_element(np.nan)
print(a.current_array)


[ nan  nan  nan  nan  nan]
this is not a legal position. position must be less then: 5
[ nan  nan  nan  nan  nan]
this is not a legal position. position must be less then: 5
[ nan  nan  nan  nan  nan]


In [ ]:
#previous code:
 
            #         for pos, ele in enumerate(self.current_array):
            #             if math.isnan(ele):
            #                 self.current_array[pos] = val
            #                 no_nan = False
            #                 break

            #         if no_nan
            #             # double the size and add the value


            #extend functionality to accommodate arbitrary position inputs          


In [50]:
x = np.empty(3)
x.fill(np.nan)
x

array([ nan,  nan,  nan])

In [52]:
x[1] = 4
np.where(x)
x[0] = 1
# x[2] =3

In [66]:
x[np.where(np.isnan(x))[0]]
x[np.isnan(x)]
# x[]

array([ nan])

In [23]:
np.append(y, x)

array([  0.,  nan,  nan,  nan])

In [27]:
x = np.array([])

In [28]:
np.where(x==math.nan)


(array([], dtype=int64),)

In [12]:
x

0

In [ ]:
def pass_param(x):
    print(x)
    type(x)
pass_param